### ISSUE TITLE
Language bug (appstrings.TranslatorException: 'English_United States' is not a valid locale string)

### ISSUE THREAD

**Issue by Aalexz** [afpineda/appstrings-python#1] opened 2024-04-14 17:07 UTC
Traceback (most recent call last):
  File "__main__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "appstrings.py", line 266, in <module>
  File "appstrings.py", line 91, in _reset
  File "appstrings.py", line 82, in _decode_locale
appstrings.TranslatorException: 'English_United States' is not a valid locale string

**Comment by afpineda** [comment] 2024-04-16 06:24
Thanks for reporting.

For some unknown reason your operating system is reporting "English_United States" as the locale string. 
It should say "**en_US**". Check your system configuration and environment variables.

In the next release, as already seen in [development branch](https://github.com/afpineda/SimWheelESP32Config/tree/Development), you will be able to force a specific language, so your issue should go away.

**Comment by afpineda** [comment] 2024-04-16 11:38
I got a jump on [release 2.1.0](https://github.com/afpineda/SimWheelESP32Config/releases/tag/2.1.0).
Now, you may work around your issue by passing "en" as a command line argument. In windows:

```shell
ESP32SimWheel.exe en
```

**Comment by Aalexz** [comment] 2024-04-16 12:52
Thanks afpineda. I did try installing different language packs first before
submitting the report.

Alex

**Comment by WallK** [comment] 2024-05-13 07:50
> I got a jump on [release 2.1.0](https://github.com/afpineda/SimWheelESP32Config/releases/tag/2.1.0). Now, you may work around your issue by passing "en" as a command line argument. In windows:
> 
> ```shell
> ESP32SimWheel.exe en
> ```

Even while passing "en" as an argument -- I get `'English_World' is not a valid locale string`
If I set English (United States) in Windows settings -- I get `'English_United States' is not a valid locale string`
In PowerShell: 
```
> Set-Culture "en_US"
> (Get-Culture).name
en-US
```

Same happens if I launch it with my own Python
```
>python src/ESP32SimWheelConfig/__main__.py es
Traceback (most recent call last):
  File "ESP32SimWheel\src\ESP32SimWheelConfig\__main__.py", line 20, in <module>
    from appstrings import gettext, set_translation_locale
  File "D:\Programs\miniconda3\envs\ESP32SimWheel\Lib\site-packages\appstrings.py", line 266, in <module>
    _reset()
  File "D:\Programs\miniconda3\envs\ESP32SimWheel\Lib\site-packages\appstrings.py", line 91, in _reset
    __current_locale = _decode_locale(getlocale()[0])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\miniconda3\envs\ESP32SimWheel\Lib\site-packages\appstrings.py", line 82, in _decode_locale
    raise TranslatorException(f"'{locale}' is not a valid locale string")
appstrings.TranslatorException: 'English_United States' is not a valid locale string
```

**Comment by afpineda** [comment] 2024-05-18 07:20
I was able to reproduce this issue:

* Operating system: Windows 11
* Language pack: English
* Country or region: United States
* Regional format: "Recommended"

```python
>>> import locale     
>>> locale.getlocale()
('English_United States', '1252')
>>>
```

Still, I don't know why the language code is not **en-US** .

**Comment by afpineda** [comment] 2024-05-18 07:41
The underlying `_locale` module seems to report the expected language code:

```python
>>> import _locale
>>> _locale._getdefaultlocale() 
('en_US', 'cp1252')
>>>
```

**Comment by afpineda** [comment] 2024-05-18 09:07
Should be fixed in appstrings version 1.0.2

**Closed as completed by afpineda** 2024-05-18 09:07 UTC

**Comment by afpineda** [comment] 2024-05-19 07:06
**Note**: There is a new release at [SimWheelESP32Config](https://github.com/afpineda/SimWheelESP32Config), where this bug was found, which should fix the original issue. Please, try.

**Comment by WallK** [comment] 2024-05-19 07:55
@afpineda without parameter and with "en" or "zh" -- it launches, thank you!
But with "es" I get:
```
Traceback (most recent call last):
  File "__main__.py", line 36, in <module>
  File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xf1' in position 14: character maps to <undefined>
```

**Comment by afpineda** [comment] 2024-05-19 14:04
> @afpineda without parameter and with "en" or "zh" -- it launches, thank you! But with "es" I get:

Good to know.

> ```
> Traceback (most recent call last):
>   File "__main__.py", line 36, in <module>
>   File "encodings\cp1251.py", line 19, in encode
> UnicodeEncodeError: 'charmap' codec can't encode character '\xf1' in position 14: character maps to <undefined>
> ```

This is another story.  That exception is OK in code page 1251. This is a minor bug caused by this line:

> print("Language: Español")

Note the *ñ* character, which is not included in code page [1252](https://en.wikipedia.org/wiki/Windows-1251).
In Windows, you may try to change the active code page to UTF-8:

> chcp 65001

But I'm not sure that will work.
Will fix it later.

Python is a pain in the ass in so many ways...

**Comment by WallK** [comment] 2024-05-19 14:33
> This is another story. That exception is OK in code page 1251. This is a minor bug caused by this line:
> 
> > print("Language: Español")
> 
> Note the _ñ_ character, which is not included in code page [1252](https://en.wikipedia.org/wiki/Windows-1251). In Windows, you may try to change the active code page to UTF-8:
> 
> > chcp 65001
> 
> But I'm not sure that will work. Will fix it later.
> 
> Python is a pain in the ass in so many ways...

You mean vice versa? 1252 has ñ, 1251 does not

```
> chcp 65001
Active code page: 65001
```
Doesn't change the error
But setting my windows to use UTF-8 for non-Unicode programs does!

>Python is a pain in the ass in so many ways...

It's more general localization, tbh
Wait till you decide to add RTL languages... (:
